#!/usr/bin/env bash
# Bash script using a while loop to display messages based on loop iteration

i=1

while [ "$i" -le 10 ]; do
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
