#!/usr/bin/env bash
# Bash script using a while loop to display time in 12-hour format

hour=0
while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    ((minute++))
  done
  ((hour++))
done
